# Site settings
title: fly.solutions
email: peter.hess@me.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pkhess.github.io/" # the base hostname & protocol for your site
twitter_username: pkhess
github_username:  pkhess

# Build settings
markdown: kramdown
